# Generated by Django 4.2.4 on 2024-05-06 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0002_customer_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='Valid',
        ),
    ]
